name: Travel Planner

on:
  pull_request:
    branches: [main, dev]

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier check
        run: npx prettier . --check

  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
